ai_settings:
  threshold: 29.0
  model_path: "results/exported_model/weights/torch/model.pt"
  test_img: "dataset/my_capsules/train/good/tic_tac_good_0_rot0_s0.9_b0.5.jpg"

camera_settings:
  device_index: 0
  width: 640
  height: 480
  default_focus: 45

kafka_settings:
  bootstrap_servers: "localhost:9092"
  raw_topic: "raw_frames"
  processed_topic: "processed_frames"

database:
  connection_string: "dbname=capsule_inspection user=admin password=password123 host=localhost"

dataset:
  name: centrum_inspection
  format: folder
  root: ./dataset/my_capsules
  normal_dir: train/good
  task: classification
  image_size: [224, 224]
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 8
  normalization: imagenet
  test_split_mode: synthetic 
  val_split_mode: same_as_test

model:
  name: patchcore
  backbone: wide_resnet50_2
  layers:
    - layer2
    - layer3
  num_neighbors: 9

trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 1
  check_val_every_n_epoch: 1

project:
  path: ./results